/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ReaderComicIdRouteImport } from './routes/reader/$comicId'
import { Route as AppWeeklyRouteImport } from './routes/_app/weekly'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppRankingRouteImport } from './routes/_app/ranking'
import { Route as AppMeRouteImport } from './routes/_app/me'
import { Route as AppListRouteImport } from './routes/_app/list'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppFavoritesRouteImport } from './routes/_app/favorites'
import { Route as AppDownloadsRouteImport } from './routes/_app/downloads'
import { Route as AppComicComicIdRouteImport } from './routes/_app/comic/$comicId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ReaderComicIdRoute = ReaderComicIdRouteImport.update({
  id: '/reader/$comicId',
  path: '/reader/$comicId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWeeklyRoute = AppWeeklyRouteImport.update({
  id: '/weekly',
  path: '/weekly',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppRankingRoute = AppRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const AppListRoute = AppListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppDownloadsRoute = AppDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => AppRoute,
} as any)
const AppComicComicIdRoute = AppComicComicIdRouteImport.update({
  id: '/comic/$comicId',
  path: '/comic/$comicId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/downloads': typeof AppDownloadsRoute
  '/favorites': typeof AppFavoritesRoute
  '/history': typeof AppHistoryRoute
  '/list': typeof AppListRoute
  '/me': typeof AppMeRoute
  '/ranking': typeof AppRankingRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/weekly': typeof AppWeeklyRoute
  '/reader/$comicId': typeof ReaderComicIdRoute
  '/comic/$comicId': typeof AppComicComicIdRoute
}
export interface FileRoutesByTo {
  '/downloads': typeof AppDownloadsRoute
  '/favorites': typeof AppFavoritesRoute
  '/history': typeof AppHistoryRoute
  '/list': typeof AppListRoute
  '/me': typeof AppMeRoute
  '/ranking': typeof AppRankingRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/weekly': typeof AppWeeklyRoute
  '/reader/$comicId': typeof ReaderComicIdRoute
  '/': typeof AppIndexRoute
  '/comic/$comicId': typeof AppComicComicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/downloads': typeof AppDownloadsRoute
  '/_app/favorites': typeof AppFavoritesRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/list': typeof AppListRoute
  '/_app/me': typeof AppMeRoute
  '/_app/ranking': typeof AppRankingRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/weekly': typeof AppWeeklyRoute
  '/reader/$comicId': typeof ReaderComicIdRoute
  '/_app/': typeof AppIndexRoute
  '/_app/comic/$comicId': typeof AppComicComicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/downloads'
    | '/favorites'
    | '/history'
    | '/list'
    | '/me'
    | '/ranking'
    | '/search'
    | '/settings'
    | '/weekly'
    | '/reader/$comicId'
    | '/comic/$comicId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/downloads'
    | '/favorites'
    | '/history'
    | '/list'
    | '/me'
    | '/ranking'
    | '/search'
    | '/settings'
    | '/weekly'
    | '/reader/$comicId'
    | '/'
    | '/comic/$comicId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/downloads'
    | '/_app/favorites'
    | '/_app/history'
    | '/_app/list'
    | '/_app/me'
    | '/_app/ranking'
    | '/_app/search'
    | '/_app/settings'
    | '/_app/weekly'
    | '/reader/$comicId'
    | '/_app/'
    | '/_app/comic/$comicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ReaderComicIdRoute: typeof ReaderComicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/reader/$comicId': {
      id: '/reader/$comicId'
      path: '/reader/$comicId'
      fullPath: '/reader/$comicId'
      preLoaderRoute: typeof ReaderComicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/weekly': {
      id: '/_app/weekly'
      path: '/weekly'
      fullPath: '/weekly'
      preLoaderRoute: typeof AppWeeklyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ranking': {
      id: '/_app/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AppRankingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/me': {
      id: '/_app/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/list': {
      id: '/_app/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof AppListRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/favorites': {
      id: '/_app/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/downloads': {
      id: '/_app/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof AppDownloadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/comic/$comicId': {
      id: '/_app/comic/$comicId'
      path: '/comic/$comicId'
      fullPath: '/comic/$comicId'
      preLoaderRoute: typeof AppComicComicIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDownloadsRoute: typeof AppDownloadsRoute
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppListRoute: typeof AppListRoute
  AppMeRoute: typeof AppMeRoute
  AppRankingRoute: typeof AppRankingRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWeeklyRoute: typeof AppWeeklyRoute
  AppIndexRoute: typeof AppIndexRoute
  AppComicComicIdRoute: typeof AppComicComicIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDownloadsRoute: AppDownloadsRoute,
  AppFavoritesRoute: AppFavoritesRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppListRoute: AppListRoute,
  AppMeRoute: AppMeRoute,
  AppRankingRoute: AppRankingRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWeeklyRoute: AppWeeklyRoute,
  AppIndexRoute: AppIndexRoute,
  AppComicComicIdRoute: AppComicComicIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ReaderComicIdRoute: ReaderComicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
