/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ReaderComicIdRouteImport } from './routes/reader/$comicId'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppFavoritesRouteImport } from './routes/_app/favorites'
import { Route as AppExploreRouteImport } from './routes/_app/explore'
import { Route as AppDownloadsRouteImport } from './routes/_app/downloads'
import { Route as AppBookshelfRouteImport } from './routes/_app/bookshelf'
import { Route as AppExploreIndexRouteImport } from './routes/_app/explore/index'
import { Route as AppExploreWeeklyRouteImport } from './routes/_app/explore/weekly'
import { Route as AppExploreSearchRouteImport } from './routes/_app/explore/search'
import { Route as AppExploreRankingRouteImport } from './routes/_app/explore/ranking'
import { Route as AppExploreListRouteImport } from './routes/_app/explore/list'
import { Route as AppComicComicIdRouteImport } from './routes/_app/comic/$comicId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ReaderComicIdRoute = ReaderComicIdRouteImport.update({
  id: '/reader/$comicId',
  path: '/reader/$comicId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppDownloadsRoute = AppDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => AppRoute,
} as any)
const AppBookshelfRoute = AppBookshelfRouteImport.update({
  id: '/bookshelf',
  path: '/bookshelf',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreIndexRoute = AppExploreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppExploreRoute,
} as any)
const AppExploreWeeklyRoute = AppExploreWeeklyRouteImport.update({
  id: '/weekly',
  path: '/weekly',
  getParentRoute: () => AppExploreRoute,
} as any)
const AppExploreSearchRoute = AppExploreSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppExploreRoute,
} as any)
const AppExploreRankingRoute = AppExploreRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AppExploreRoute,
} as any)
const AppExploreListRoute = AppExploreListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => AppExploreRoute,
} as any)
const AppComicComicIdRoute = AppComicComicIdRouteImport.update({
  id: '/comic/$comicId',
  path: '/comic/$comicId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/bookshelf': typeof AppBookshelfRoute
  '/downloads': typeof AppDownloadsRoute
  '/explore': typeof AppExploreRouteWithChildren
  '/favorites': typeof AppFavoritesRoute
  '/settings': typeof AppSettingsRoute
  '/reader/$comicId': typeof ReaderComicIdRoute
  '/comic/$comicId': typeof AppComicComicIdRoute
  '/explore/list': typeof AppExploreListRoute
  '/explore/ranking': typeof AppExploreRankingRoute
  '/explore/search': typeof AppExploreSearchRoute
  '/explore/weekly': typeof AppExploreWeeklyRoute
  '/explore/': typeof AppExploreIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/bookshelf': typeof AppBookshelfRoute
  '/downloads': typeof AppDownloadsRoute
  '/favorites': typeof AppFavoritesRoute
  '/settings': typeof AppSettingsRoute
  '/reader/$comicId': typeof ReaderComicIdRoute
  '/': typeof AppIndexRoute
  '/comic/$comicId': typeof AppComicComicIdRoute
  '/explore/list': typeof AppExploreListRoute
  '/explore/ranking': typeof AppExploreRankingRoute
  '/explore/search': typeof AppExploreSearchRoute
  '/explore/weekly': typeof AppExploreWeeklyRoute
  '/explore': typeof AppExploreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/bookshelf': typeof AppBookshelfRoute
  '/_app/downloads': typeof AppDownloadsRoute
  '/_app/explore': typeof AppExploreRouteWithChildren
  '/_app/favorites': typeof AppFavoritesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/reader/$comicId': typeof ReaderComicIdRoute
  '/_app/': typeof AppIndexRoute
  '/_app/comic/$comicId': typeof AppComicComicIdRoute
  '/_app/explore/list': typeof AppExploreListRoute
  '/_app/explore/ranking': typeof AppExploreRankingRoute
  '/_app/explore/search': typeof AppExploreSearchRoute
  '/_app/explore/weekly': typeof AppExploreWeeklyRoute
  '/_app/explore/': typeof AppExploreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/bookshelf'
    | '/downloads'
    | '/explore'
    | '/favorites'
    | '/settings'
    | '/reader/$comicId'
    | '/comic/$comicId'
    | '/explore/list'
    | '/explore/ranking'
    | '/explore/search'
    | '/explore/weekly'
    | '/explore/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/bookshelf'
    | '/downloads'
    | '/favorites'
    | '/settings'
    | '/reader/$comicId'
    | '/'
    | '/comic/$comicId'
    | '/explore/list'
    | '/explore/ranking'
    | '/explore/search'
    | '/explore/weekly'
    | '/explore'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/bookshelf'
    | '/_app/downloads'
    | '/_app/explore'
    | '/_app/favorites'
    | '/_app/settings'
    | '/reader/$comicId'
    | '/_app/'
    | '/_app/comic/$comicId'
    | '/_app/explore/list'
    | '/_app/explore/ranking'
    | '/_app/explore/search'
    | '/_app/explore/weekly'
    | '/_app/explore/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ReaderComicIdRoute: typeof ReaderComicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/reader/$comicId': {
      id: '/reader/$comicId'
      path: '/reader/$comicId'
      fullPath: '/reader/$comicId'
      preLoaderRoute: typeof ReaderComicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/favorites': {
      id: '/_app/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explore': {
      id: '/_app/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/downloads': {
      id: '/_app/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof AppDownloadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bookshelf': {
      id: '/_app/bookshelf'
      path: '/bookshelf'
      fullPath: '/bookshelf'
      preLoaderRoute: typeof AppBookshelfRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explore/': {
      id: '/_app/explore/'
      path: '/'
      fullPath: '/explore/'
      preLoaderRoute: typeof AppExploreIndexRouteImport
      parentRoute: typeof AppExploreRoute
    }
    '/_app/explore/weekly': {
      id: '/_app/explore/weekly'
      path: '/weekly'
      fullPath: '/explore/weekly'
      preLoaderRoute: typeof AppExploreWeeklyRouteImport
      parentRoute: typeof AppExploreRoute
    }
    '/_app/explore/search': {
      id: '/_app/explore/search'
      path: '/search'
      fullPath: '/explore/search'
      preLoaderRoute: typeof AppExploreSearchRouteImport
      parentRoute: typeof AppExploreRoute
    }
    '/_app/explore/ranking': {
      id: '/_app/explore/ranking'
      path: '/ranking'
      fullPath: '/explore/ranking'
      preLoaderRoute: typeof AppExploreRankingRouteImport
      parentRoute: typeof AppExploreRoute
    }
    '/_app/explore/list': {
      id: '/_app/explore/list'
      path: '/list'
      fullPath: '/explore/list'
      preLoaderRoute: typeof AppExploreListRouteImport
      parentRoute: typeof AppExploreRoute
    }
    '/_app/comic/$comicId': {
      id: '/_app/comic/$comicId'
      path: '/comic/$comicId'
      fullPath: '/comic/$comicId'
      preLoaderRoute: typeof AppComicComicIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppExploreRouteChildren {
  AppExploreListRoute: typeof AppExploreListRoute
  AppExploreRankingRoute: typeof AppExploreRankingRoute
  AppExploreSearchRoute: typeof AppExploreSearchRoute
  AppExploreWeeklyRoute: typeof AppExploreWeeklyRoute
  AppExploreIndexRoute: typeof AppExploreIndexRoute
}

const AppExploreRouteChildren: AppExploreRouteChildren = {
  AppExploreListRoute: AppExploreListRoute,
  AppExploreRankingRoute: AppExploreRankingRoute,
  AppExploreSearchRoute: AppExploreSearchRoute,
  AppExploreWeeklyRoute: AppExploreWeeklyRoute,
  AppExploreIndexRoute: AppExploreIndexRoute,
}

const AppExploreRouteWithChildren = AppExploreRoute._addFileChildren(
  AppExploreRouteChildren,
)

interface AppRouteChildren {
  AppBookshelfRoute: typeof AppBookshelfRoute
  AppDownloadsRoute: typeof AppDownloadsRoute
  AppExploreRoute: typeof AppExploreRouteWithChildren
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppComicComicIdRoute: typeof AppComicComicIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBookshelfRoute: AppBookshelfRoute,
  AppDownloadsRoute: AppDownloadsRoute,
  AppExploreRoute: AppExploreRouteWithChildren,
  AppFavoritesRoute: AppFavoritesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppComicComicIdRoute: AppComicComicIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ReaderComicIdRoute: ReaderComicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
